version: 2 

sources:
  - name: tlc_taxi_trips
    meta:
      external_location: 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet'
      formatter: oldstyle
    tables:
      - name: raw_yellow_tripdata
      

